#!/usr/bin/env python3
"""Propose an Engineering Harness profile and detect meaningful profile drift."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from validate_profile import validate_profile


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / ".codex-plugin" / "plugin.json"
ACTIVATION = ROOT / "references" / "capability-activation.json"
CATALOG = ROOT / "references" / "invariants.json"
EXCLUDED_PARTS = {
    ".cxx",
    ".dart_tool",
    ".git",
    ".idea",
    ".venv",
    ".vscode",
    "build",
    "coverage",
    "assets",
    "data",
    "dist",
    "docs",
    "ephemeral",
    "evals",
    "examples",
    "integration_test",
    "node_modules",
    "references",
    "skills",
    "templates",
    "test",
    "tests",
    "third_party",
    "_deps",
    "vendor",
    "venv",
}
TEXT_SUFFIXES = {
    ".c",
    ".cc",
    ".cpp",
    ".cs",
    ".dart",
    ".go",
    ".gradle",
    ".h",
    ".hpp",
    ".java",
    ".js",
    ".json",
    ".jsx",
    ".kt",
    ".kts",
    ".php",
    ".py",
    ".rb",
    ".rs",
    ".sh",
    ".swift",
    ".toml",
    ".ts",
    ".tsx",
    ".yaml",
    ".yml",
}
MAX_FILE_BYTES = 512 * 1024
SCANNER_VERSION = 4
CLIENT_SURFACE_FAMILIES = {
    "desktop": ("desktop",),
    "mobile": ("android", "ios", "mobile"),
    "web": ("frontend", "web"),
}
AI_PROVIDER_TERMS = (
    "import openai",
    "from openai",
    "@anthropic-ai/",
    "package:google_generative_ai/",
    "generativelanguage.googleapis.com",
)
AI_ACTION_TERMS = (
    "execute_action",
    "tool_call",
    "apply_proposal",
    "approval_required",
)
AI_ACTION_PATH = re.compile(
    r"(^|/)(assistant|ai[_-]?actions?|model[_-]?providers?)(/|[._-])"
)


@dataclass(frozen=True)
class SignalRule:
    capability: str
    name: str
    weight: int
    path_pattern: str | None = None
    content_terms: tuple[str, ...] = ()
    require_all_terms: bool = False


RULES = (
    SignalRule("durable_work", "durable-owner-path", 4, r"(^|/)(jobs?|queues?|workers?|workflows?|schedulers?|outbox)(/|[._-])"),
    SignalRule("durable_work", "durable-runtime-dependency", 4, content_terms=("temporalio", "dbos", "workmanager", "bullmq", "celery")),
    SignalRule("durable_work", "checkpointed-retry-code", 2, content_terms=("checkpoint", "retry"), require_all_terms=True),
    SignalRule("offline_operation", "offline-storage-dependency", 4, content_terms=("sqflite", "roomdatabase", "coredata", "package:drift/")),
    SignalRule("offline_operation", "offline-owner-path", 3, r"(^|/)(offline|local[_-]?database|local[_-]?store)(/|[._-])"),
    SignalRule("replicated_state", "replication-owner-path", 4, r"(^|[/_.-])(sync|replication|reconciliation|tombstones?|outbox)([/_.-]|$)"),
    SignalRule("replicated_state", "replication-contract-code", 3, content_terms=("tombstone", "sync cursor", "replication cursor")),
    SignalRule("external_providers", "provider-adapter-path", 4, r"(^|[/_.-])(providers?|integrations?|connectors?)([/_.-]|$)"),
    SignalRule("external_providers", "oauth-boundary", 3, content_terms=("oauth2", "authorization_code", "client_credentials")),
    SignalRule("generated_artifacts", "generated-marker", 4, content_terms=("generated by", "do not edit"), require_all_terms=True),
    SignalRule("generated_artifacts", "generator-owner-path", 2, r"(^|/)(generators?|generate[_-][^/]+)(/|[._-])"),
    SignalRule("generated_artifacts", "generated-output-path", 2, r"(^|/)(generated|generated[_-][^/]+)(/|[._-])"),
    SignalRule("physical_devices", "hardware-or-firmware-project", 4, r"(^|/)(firmware|hardware)(/|$)"),
    SignalRule("physical_devices", "physical-design-source", 4, r"\.(scad|kicad_sch|kicad_pcb)$"),
    SignalRule("artifact_publication", "publish-workflow", 4, r"(^|/)(\.github/workflows/[^/]*publish|publish|publishing|app[_-]?store|play[_-]?store)(/|[._-])"),
    SignalRule("mutable_authority_context", "account-or-tenant-context", 4, r"(^|[/_.-])(account|tenant)[_-]?(context|epoch|scope)([/_.-]|$)"),
    SignalRule("event_delivery", "event-model-path", 1, r"(^|[/_.-])events?([/_.-]|$)"),
    SignalRule("event_delivery", "event-delivery-path", 4, r"(^|[/_.-])(sse|websocket|outbox|inbox)([/_.-]|$)"),
    SignalRule("event_delivery", "stream-transport-code", 4, content_terms=("text/event-stream", "websocketchannel")),
    SignalRule("interactive_clients", "interactive-framework", 4, content_terms=("package:flutter/", "react-dom", "@angular/core", "from 'vue'", "from \"vue\"")),
    SignalRule("interactive_clients", "interactive-client-path", 3, r"(^|/)(web|mobile|frontend|screens?|widgets?)(/|[._-])"),
    SignalRule("asynchronous_interactive_loading", "async-ui-code", 3, content_terms=("futurebuilder", "suspense", "useeffect", "asyncvalue")),
    SignalRule("shared_nonpreemptible_storage", "sqlite-writer", 4, content_terms=("sqflite", "better-sqlite3")),
    SignalRule("constrained_runtime_resources", "runtime-resource-owner", 4, r"(^|/)(runtime[_-]?resource[_-]?(manager|governor)|resource[_-]?(budget|pool|governor)|buffer[_-]?pool)(/|[._-])"),
    SignalRule("constrained_runtime_resources", "protected-resource-policy", 2, content_terms=("protected reserve", "cooperative stop"), require_all_terms=True),
    SignalRule("multiple_adapters", "adapter-path", 2, r"(^|/)(adapters?|ports?)(/|[._-])"),
    SignalRule("shared_production_state", "deployment-config", 2, r"(^|/)(terraform|k8s|kubernetes|deploy|cloudrun)(/|[._-])"),
    SignalRule("shared_production_state", "server-database", 2, content_terms=("postgres", "mysql", "cockroachdb")),
)


def package_version() -> str:
    return json.loads(MANIFEST.read_text(encoding="utf-8"))["version"]


def _iter_files(repository: Path) -> Iterable[tuple[str, str]]:
    for path in sorted(repository.rglob("*")):
        if not path.is_file() or path.is_symlink():
            continue
        relative = path.relative_to(repository)
        if any(part in EXCLUDED_PARTS for part in relative.parts):
            continue
        if relative.as_posix() == "scripts/profile_repository.py":
            continue
        if path.name == "GeneratedPluginRegistrant.java":
            continue
        if path.suffix.lower() not in TEXT_SUFFIXES and path.name not in {
            "Dockerfile",
            "Gemfile",
            "Makefile",
            "Podfile",
            "pubspec.yaml",
        }:
            continue
        try:
            if path.stat().st_size > MAX_FILE_BYTES:
                continue
            yield relative.as_posix(), path.read_text(encoding="utf-8").lower()
        except (OSError, UnicodeDecodeError):
            continue


def _rule_match(rule: SignalRule, relative: str, content: str) -> bool:
    first = relative.split("/", 1)[0]
    if first == "scripts" and rule.capability not in {"generated_artifacts", "artifact_publication"}:
        return False
    if first == "deploy" and rule.capability not in {"generated_artifacts", "artifact_publication", "shared_production_state"}:
        return False
    if rule.path_pattern and re.search(rule.path_pattern, relative.lower()):
        return True
    if not rule.content_terms:
        return False
    matches = [term in content for term in rule.content_terms]
    return all(matches) if rule.require_all_terms else any(matches)


def _confidence(score: int) -> str:
    if score >= 4:
        return "high"
    if score >= 2:
        return "medium"
    if score == 1:
        return "low"
    return "none"


def scan_repository(repository: Path) -> dict[str, object]:
    files = sorted(_iter_files(repository), key=lambda item: _evidence_rank(item[0]))
    activation = json.loads(ACTIVATION.read_text(encoding="utf-8"))
    findings: dict[str, dict[str, object]] = {
        name: {"suggested": False, "confidence": "none", "evidence": []}
        for name in activation["capabilities"]
    }
    scores = {name: 0 for name in findings}

    for rule in RULES:
        for relative, content in files:
            if _rule_match(rule, relative, content):
                scores[rule.capability] += rule.weight
                evidence = findings[rule.capability]["evidence"]
                assert isinstance(evidence, list)
                evidence.append({"rule": rule.name, "path": relative})
                break

    # Action authority is one execution path, not a repository-wide sum of an
    # unrelated provider import and an unrelated command named "execute_action".
    for relative, content in files:
        has_provider = any(term in content for term in AI_PROVIDER_TERMS)
        has_action = any(term in content for term in AI_ACTION_TERMS)
        has_action_owner = bool(AI_ACTION_PATH.search(relative.lower()))
        if (has_provider and has_action) or (has_action_owner and has_action):
            scores["ai_mediated_actions"] = 4
            findings["ai_mediated_actions"]["evidence"] = [
                {"rule": "ai-action-owner-code", "path": relative}
            ]
            break

    client_paths: dict[str, str] = {}
    for relative, _ in files:
        for family, markers in CLIENT_SURFACE_FAMILIES.items():
            if any(
                re.search(rf"(^|/){marker}(/|$)", relative.lower())
                for marker in markers
            ):
                client_paths.setdefault(family, relative)
    if len(client_paths) >= 2:
        scores["multiple_clients"] = 4
        findings["multiple_clients"]["evidence"] = [
            {"rule": f"client-surface-{family}", "path": relative}
            for family, relative in sorted(client_paths.items())
        ]

    adapter_paths = sorted(
        {
            relative
            for relative, _ in files
            if re.search(r"(^|[/_.-])(adapters?|ports?)([/_.-]|$)", relative.lower())
        }
    )
    if len(adapter_paths) >= 2:
        scores["multiple_adapters"] = 4
        findings["multiple_adapters"]["evidence"] = [
            {"rule": "multiple-adapter-files", "path": path}
            for path in adapter_paths[:4]
        ]

    if scores["interactive_clients"] >= 4 and scores["asynchronous_interactive_loading"] >= 2:
        scores["asynchronous_interactive_loading"] = 4

    if not (scores["shared_production_state"] >= 4):
        scores["shared_production_state"] = 0
        findings["shared_production_state"]["evidence"] = []

    sensitive_evidence = []
    for relative, content in files:
        if any(term in content for term in ("health data", "medical", "payment", "patient", "protected data")):
            sensitive_evidence.append({"rule": "sensitive-domain-code", "path": relative})
            break
    sensitive_confidence = "high" if sensitive_evidence else "none"

    for name, score in scores.items():
        confidence = _confidence(score)
        findings[name]["confidence"] = confidence
        findings[name]["suggested"] = confidence == "high"

    return {
        "scanner_version": SCANNER_VERSION,
        "repository_revision": _repository_revision(repository),
        "project_fields": {
            "sensitive_data": {
                "suggested": sensitive_confidence == "high",
                "confidence": sensitive_confidence,
                "evidence": sensitive_evidence,
            }
        },
        "capabilities": findings,
    }


def _evidence_rank(relative: str) -> tuple[int, str]:
    name = Path(relative).name
    if name in {"package.json", "pubspec.yaml", "pyproject.toml", "Cargo.toml", "build.gradle", "build.gradle.kts"}:
        return (0, relative)
    if any(part in {"lib", "src", "server", "api", "web", "mobile"} for part in Path(relative).parts):
        return (1, relative)
    return (2, relative)


def _repository_revision(repository: Path) -> str:
    result = subprocess.run(
        ["git", "-C", str(repository), "rev-parse", "HEAD"],
        capture_output=True,
        check=False,
        text=True,
    )
    revision = result.stdout.strip()
    return revision if result.returncode == 0 and re.fullmatch(r"[0-9a-f]{40}", revision) else "unversioned"


def _discover_sources(repository: Path) -> dict[str, str]:
    candidates = {
        "agent_rules": ("AGENTS.md", "CLAUDE.md"),
        "architecture": ("DESIGN.md", "ARCHITECTURE.md", "README.md"),
        "work_tracker": ("TODO.md",),
        "compatibility": ("compatibility_manifest.json",),
        "acceptance_contracts": ("acceptance_contracts.json", "docs/acceptance_contracts.json"),
        "operator_interface": ("vt", "Makefile", "package.json", "pyproject.toml"),
    }
    sources: dict[str, str] = {}
    for name, paths in candidates.items():
        for relative in paths:
            if (repository / relative).exists():
                sources[name] = f"./{relative}" if name == "operator_interface" else relative
                break
    return sources


def propose_profile(repository: Path) -> dict[str, object]:
    discovery = scan_repository(repository)
    project_fields = discovery["project_fields"]
    capability_findings = discovery["capabilities"]
    assert isinstance(project_fields, dict) and isinstance(capability_findings, dict)
    sensitive = bool(project_fields["sensitive_data"]["suggested"])
    capabilities = {
        name: bool(finding["suggested"])
        for name, finding in capability_findings.items()
    }
    active = set(json.loads(ACTIVATION.read_text(encoding="utf-8"))["always"])
    activation = json.loads(ACTIVATION.read_text(encoding="utf-8"))
    if sensitive:
        active.update(activation["project_fields"].get("sensitive_data", []))
    for name, enabled in capabilities.items():
        if enabled:
            active.update(activation["capabilities"][name])

    catalog = {
        item["id"]: item for item in json.loads(CATALOG.read_text(encoding="utf-8"))["invariants"]
    }
    enforcement = {
        invariant_id: {"rung": "principle", "owner": "review-required"}
        for invariant_id in sorted(active)
        if invariant_id in catalog
    }
    kind = "single-process-application"
    if capabilities.get("multiple_clients"):
        kind = "multi-client-application"
    if capabilities.get("offline_operation") and capabilities.get("replicated_state"):
        kind = "local-first-application"

    return {
        "schema_version": 2,
        "harness_policy_version": package_version(),
        "status": "proposed",
        "project": {
            "name": repository.resolve().name,
            "kind": kind,
            "sensitive_data": sensitive,
        },
        "sources": _discover_sources(repository),
        "capabilities": capabilities,
        "enforcement": enforcement,
        "exceptions": [],
        "discovery": discovery,
    }


def _policy_line(version: str) -> tuple[int, ...]:
    major, minor, _ = (int(part) for part in version.split("."))
    return (major, minor) if major == 0 else (major,)


def check_drift(repository: Path, profile: dict[str, object]) -> tuple[list[str], list[str]]:
    errors = validate_profile(profile)
    warnings: list[str] = []
    if errors:
        return errors, warnings
    if profile["status"] != "accepted":
        errors.append("profile status is proposed; review and accept it before drift checks gate work")

    recorded_version = str(profile["harness_policy_version"])
    current_version = package_version()
    if _policy_line(recorded_version) != _policy_line(current_version):
        errors.append(
            f"harness policy line changed: profile={recorded_version} package={current_version}; apply migration notes"
        )

    for name, relative in profile["sources"].items():
        candidate = relative.split("#", 1)[0]
        candidate = candidate[2:] if candidate.startswith("./") else candidate
        if not (repository / candidate).exists():
            errors.append(f"recorded source is missing: {name}={relative}")

    current = scan_repository(repository)
    current_capabilities = current["capabilities"]
    recorded_capabilities = profile["capabilities"]
    for name, finding in current_capabilities.items():
        if finding["suggested"] and not recorded_capabilities[name]:
            paths = ", ".join(item["path"] for item in finding["evidence"][:3])
            errors.append(f"new high-confidence capability: {name} ({paths})")
        elif recorded_capabilities[name] and finding["confidence"] == "none":
            warnings.append(f"recorded capability has no current detector evidence: {name}")

    current_sensitive = current["project_fields"]["sensitive_data"]
    if current_sensitive["suggested"] and not profile["project"]["sensitive_data"]:
        errors.append("new high-confidence sensitive-data signal")
    return errors, warnings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("repository", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", type=Path, metavar="PROFILE")
    args = parser.parse_args(argv)
    repository = args.repository.resolve()
    if not repository.is_dir():
        print(f"not a repository directory: {repository}", file=sys.stderr)
        return 2

    if args.check:
        try:
            profile = json.loads(args.check.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            print(error, file=sys.stderr)
            return 2
        errors, warnings = check_drift(repository, profile)
        for warning in warnings:
            print(f"WARNING: {warning}")
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        if errors:
            return 1
        print(f"profile current for harness policy {package_version()}")
        return 0

    document = propose_profile(repository)
    rendered = json.dumps(document, indent=2, sort_keys=False) + "\n"
    if args.output:
        args.output.write_text(rendered, encoding="utf-8")
        print(f"wrote proposed profile: {args.output}")
    else:
        print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
