#!/usr/bin/env python3
"""Render the human-readable invariant catalog from its JSON authority."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "references" / "invariants.json"
OUTPUT = ROOT / "references" / "engineering-invariants.md"


def render() -> str:
    document = json.loads(SOURCE.read_text(encoding="utf-8"))
    lines = [
        "# Engineering Invariants",
        "",
        "<!-- Generated by scripts/render_invariants.py; edit invariants.json. -->",
        "",
        "A project activates only the invariants its real capabilities require and",
        "records each current rung using the enforcement ladder.",
        "",
        "| # | Invariant | Activates when | Default rung | Owning skills |",
        "| -: | --- | --- | --- | --- |",
    ]
    for index, item in enumerate(document["invariants"], start=1):
        statement = item["statement"].replace("|", "\\|")
        activation = item["activates_when"].replace("|", "\\|")
        skills = ", ".join(f"`{name}`" for name in item["skills"])
        lines.append(
            f"| {index} | **`{item['id']}`**: {statement} | "
            f"{activation} | `{item['default_rung']}` | {skills} |"
        )
    lines.extend(
        [
            "",
            "The default rung is a starting recommendation, not a claim about a",
            "repository's current enforcement. The project profile records reality.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"stale generated file: {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"current: {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
